default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3
  
production:
  adapter: postgresql
  encoding: unicode
  database: postgres_production
  pool: 5
  username: postgres
